### PR TITLE
Template updates to support new resource framework and modeling tutorial

### PR DESCRIPTION
**Pull request by ewferg**
Docker compose version bump to v2.3.0
Change template project name to mission model
Update mission class to support new resource framework 
Removed activity and resource examples to back the template a true blank slate 
Added merlin driver as a dependency

### CODE REVIEW

**Comment by ewferg** [comment]
Note I tested these changes locally and the model builds, uploads, and simulates (albeit a boring simulation since there are no activities or resources) successfully

**Review by bradNASA — COMMENTED** [review]
I didn't run it, but it looks fine to me.  "Firesat" is mentioned in two or three places in https://github.com/NASA-AMMOS/multi-mission-utilities-DSN . The [fast-track tutorial](https://nasa-ammos.github.io/aerie-docs/planning/upload-mission-model/) mentions "firesat," has "firesat" in the videos, and shows the now-removed `GncControlMode` and a now-removed `GncChangeControlMode` activity.  So, that would need updating.

I wonder if the user might be confused that the model doesn't do anything.  Do you intend to integrate one or more of the simple models into this one?

**Comment by ewferg** [comment]
> I didn't run it, but it looks fine to me. "Firesat" is mentioned in two or three places in https://github.com/NASA-AMMOS/multi-mission-utilities-DSN . The [fast-track tutorial](https://nasa-ammos.github.io/aerie-docs/planning/upload-mission-model/) mentions "firesat," has "firesat" in the videos, and shows the now-removed `GncControlMode` and a now-removed `GncChangeControlMode` activity. So, that would need updating.
> 
> I wonder if the user might be confused that the model doesn't do anything. Do you intend to integrate one or more of the simple models into this one?

Thanks for the review @bradNASA. I'll clean up the other references to firesat in the [DSN utilities](https://github.com/NASA-AMMOS/multi-mission-utilities-DSN) and docs. 

I keep going back and forth about whether it makes sense to include something in the template or if it should really be a "blank slate" repo. I think we are getting close to building our first simple spacecraft model that leverages our simple subsystem models. I think pointing to this simple spacecraft model in the fast track tutorial would be a good option. We also have other models that users can use as examples now. Given that, I have been leaning towards keeping the template empty for modelers who want to to start from scratch, but not have to worry about setting up gradle dependencies, etc. Does anyone have strong opinions towards keeping some resources/activities in this template?

**Review by dandelany — APPROVED** [review]
This looks good to me @ewferg and I successfully used it in my run through of the tutorial. I pushed a couple small changes to the readme:
- removed bash comment - only works if on its own line
- commented out reference to the included `.jar` file since it no longer exists. I'm not sure if it's a good idea or not to include a pre-built jar, since it's easy for the user to mistake it for the one in `build/lib`. Maybe if we put it in a less obvious place eg. `example-build` folder...

re: your question:
> Does anyone have strong opinions towards keeping some resources/activities in this template?

I think it's a good idea to keep the Mission model itself as a "blank slate" for the sake of the tutorial. However, I think including some simple examples of activities/resources/etc somewhere in this repo (eg. an `/examples` folder) would be very useful for learning & fighting "blank page syndrome". They don't have to be included in the main model, just there to give people something to start working from. I think the Simple Spacecraft Model that the WG is working on will be another useful source, but we almost need some examples here that are even simpler than the "simple" model (not for this PR though).

**Pull request merged**
